name: Build blend_env image

env:
  DOCKERHUB_USERNAME: luciusm
  IMAGE_NAME: blender-env
  TEST_TAG: blender-env:tests
  LATEST_VERSION: "3.6"

on:
  push:
    branches:
      - main
      - workflow
    paths:
      - "Dockerfiles/Dockerfile.base**"
      - ".github/workflows/build_blender_env_image.yml"
  workflow_dispatch:

jobs:
  build_blender_env_versioned:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Manually change these to match the blender image versions
        # Blender 3.3 seems to break
        blender-version: ["3.0", "3.1", "3.2", "3.4", "3.5", "3.6"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders || :
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      - name: Login to Github Container Repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set lower case repository name
        # Hit from https://github.community/t/github-actions-repository-name-must-be-lowercase/184924
        run: |
          echo "REPO_OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
      - name: Name conversion between ghcr & dockerhub. Replace - with _
        run: |
          echo "DOCKERHUB_IMAGE_NAME=${IMG/-/_}" >> ${GITHUB_ENV}
        env:
          IMG: "${{ env.IMAGE_NAME }}"
      - name: Build and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: ./
          # file: ./Dockerfiles/Dockerfile.base_3.x
          file: ./Dockerfiles/Dockerfile.env
          push: true
          build-args: BLENDER_VERSION=${{ matrix.blender-version }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:blender${{ matrix.blender-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Tag latest image GHCR
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:blender${{ matrix.blender-version }}
          dst: ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:latest
        if: ${{ matrix.blender-version == env.LATEST_VERSION }}
      # Keep the dockerhub images just for backward compatibility check. Ok to fail
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Copy images between GHCR and Dockerhub
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:blender${{ matrix.blender-version }}
          dst: docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}:blender${{ matrix.blender-version }}
